# Generated by Django 3.1.2 on 2020-11-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('date_of_birth', models.DateField(max_length=225)),
                ('weight', models.CharField(max_length=225)),
                ('height', models.CharField(max_length=225)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=225)),
                ('food_allergies', models.CharField(max_length=225)),
                ('medication_allergies', models.CharField(max_length=225)),
                ('primary_doctor', models.CharField(max_length=225)),
                ('primary_doctor_telephone_number', models.CharField(max_length=225)),
                ('language', models.CharField(max_length=225)),
                ('bed_patient', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=225)),
                ('walking_assistant_devices', models.CharField(max_length=225)),
            ],
        ),
    ]
