# Generated by Django 3.1.2 on 2020-11-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20201102_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='upload',
        ),
    ]
