# Generated by Django 3.1.2 on 2020-11-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='walking_assistant_devices',
        ),
        migrations.AddField(
            model_name='patient',
            name='walking_devices',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='able_to_walk_alone',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='food_allergies',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_allergies',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
