# Generated by Django 3.1.2 on 2020-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20201103_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='food_allergies',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication_allergies',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='walking_devices',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
