# Generated by Django 3.1.2 on 2020-11-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20201103_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='able_to_walk_alone',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=225),
        ),
    ]
