# Generated by Django 3.1.2 on 2020-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20201103_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='able_to_walk_alone',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed_patient',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=225),
        ),
    ]
