# Generated by Django 3.1.2 on 2020-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20201103_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='able_to_walk_alone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bed_patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_bed_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='needs_walking_device',
            field=models.BooleanField(default=False),
        ),
    ]
