# Generated by Django 3.1.2 on 2020-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20201103_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='patients/'),
        ),
    ]
