# Generated by Django 3.1.2 on 2020-11-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20201104_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_address',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
