# Generated by Django 3.1.2 on 2020-11-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20201104_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
    ]
