# Generated by Django 3.1.2 on 2020-11-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20201106_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='hourly_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='take_as_needed',
            field=models.BooleanField(default=False),
        ),
    ]
