# Generated by Django 3.1.3 on 2020-11-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='walking_devices',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
