# Generated by Django 3.1.3 on 2020-11-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_patient_caregiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='caregiver',
            new_name='caregivers',
        ),
    ]
